Repository wldud7788/fire-spot, pull requests merged in 2024-11, with the labels that each got.

#33 캘린더 데이터 불러올때 meet가 아닌 meet_attendee기준으로 불러오도록 수정
  public/assets/images/ico-next.svg
  public/assets/images/ico-prev.svg
  src/_components/calendar/Calendar.tsx
  src/_components/calendar/CalendarCell.tsx
  src/_components/calendar/CalendarHeader.tsx
  src/_components/calendar/CalendarTable.tsx
  src/_components/calendar/action/calendarAction.ts
  src/app/(pages)/meets/hooks/useMeetCreatorForm.ts
  tailwind.config.ts
Labels: 수정

#34 모임 관련 미들웨어 처리
  src/_utils/supabase/middleware.ts
  src/app/(pages)/meets/[meetId]/page.tsx
  src/app/(pages)/meets/actions/meetDetailAction.ts
  src/app/(pages)/meets/edit/[meetId]/page.tsx
  src/app/(pages)/meets/hooks/useMeetCreatorForm.ts
  src/app/(pages)/meets/utils/processSubmitData.ts
  src/middleware.ts
Labels: 완료

#53 [Feat/map] 캠핑장 상세 페이지 지도 기능 추가 및 검색 필터 개선
  package.json
  pnpm-lock.yaml
  src/_components/camp/CampDetail.tsx
  src/_components/search/searchBar/style.ts
  src/_hooks/useBaseMap.ts
  src/_utils/supabase/client.ts
  src/app/(pages)/camp-detail/components/DetailMap.tsx
  src/app/(pages)/camp-detail/hooks/useCampDetilMap.ts
  src/app/(pages)/search/components/CampCard.tsx
  src/app/(pages)/search/components/SearchResults.tsx
  src/app/(pages)/search/constants/filterOptions.ts
  src/app/(pages)/search/hooks/useFilters.ts
  src/app/(pages)/search/hooks/useSearchMap.ts
  src/app/(pages)/search/page.tsx
  src/app/api/camping/route.ts
  src/app/globals.css
  src/type/map.ts
  yarn.lock
Labels: bug, refactor, feat

#55 [style/all] 캠핑장 리스트, 상세 페이지 스타일 1차 완료
  public/assets/images/camp/ico-camp-list-bookmark-on.svg
  public/assets/images/camp/ico-camp-list-bookmark.svg
  public/assets/images/common/ico-checkbox-on.svg
  public/assets/images/common/ico-checkbox.svg
  public/assets/images/common/ico-pagination-arrow.svg
  src/_components/camp/CampCard.tsx
  src/_components/camp/CampDetail.tsx
  src/_components/camp/CampList.tsx
  src/_components/common/PageTitle.tsx
  src/_components/pagination/Pagination.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: style

#56 [Feat/search] : 검색 기능 개선 및 컴포넌트 구조 정리
  src/_components/main/MainSearch.tsx
  src/_components/search/dropdown/DropDownSearch.tsx
  src/app/(pages)/search/components/SearchHeader.tsx
  src/app/(pages)/search/components/SearchList.tsx
  src/app/(pages)/search/components/SearchResults.tsx
  src/app/(pages)/search/hooks/useFilters.ts
Labels: 리팩토링, 기능개발

#61 [style/all] 마이페이지>팔로워 1차 스타일 처리 완료
  public/assets/images/camp/btn-camp-bookmark.svg
  public/assets/images/camp/btn-camp-share.svg
  public/assets/images/camp/ico-camp-chk.svg
  public/assets/images/camp/ico-camp-tit01.svg
  public/assets/images/camp/ico-camp-tit02.svg
  public/assets/images/camp/ico-camp-tit03.svg
  public/assets/images/camp/ico-camp-tit04.svg
  public/assets/images/camp/ico-camp-tit05.svg
  public/assets/images/camp/ico-camp-tit06.svg
  public/assets/images/camp/ico-camp-tit07.svg
  public/assets/images/common/ico-import.svg
  public/assets/images/common/ico-plus-c.svg
  public/assets/images/common/ico-polygon.svg
  public/assets/images/common/ico-star-c-big.svg
  public/assets/images/logo.svg
  public/assets/images/main/ico-search-arrow.svg
  public/assets/images/mypage/ico-mypage-bookmark.svg
  public/assets/images/mypage/ico-mypage-meet.svg
  public/assets/images/mypage/ico-mypage-stamp.svg
  src/_components/camp/CampDetail.tsx
  src/_components/camp/CampNoData.tsx
  src/_components/follower/FollowButton.tsx
  src/_components/follower/FollowCard.tsx
  src/_components/follower/FollowForm.tsx
  src/_components/follower/FollowsCount.tsx
  src/_components/layout/Header.tsx
  src/_components/main/MainCamps.tsx
  src/_components/main/MainSearch.tsx
  src/_components/main/MainUserCard.tsx
  src/app/(pages)/mypage/Followers.tsx
  src/app/(pages)/mypage/TabList.tsx
  src/app/(pages)/mypage/UserCard.tsx
  src/app/(pages)/mypage/page.tsx
  src/app/globals.css
  src/app/page.tsx
  tailwind.config.ts
Labels: 스타일

#74 [style/all] 모임 스타일 1차 완료
  public/assets/images/common/ico-heart.svg
  public/assets/images/common/ico-pin.svg
  public/assets/images/common/ico-share.svg
  public/assets/images/ico-date.svg
  public/assets/images/ico-group.svg
  public/assets/images/ico-location.svg
  public/assets/images/meet/ico-import.svg
  public/assets/images/meet/ico-meet-avatar.svg
  public/assets/images/meet/ico-meet-calendar.svg
  public/assets/images/meet/ico-meet-category.svg
  public/assets/images/meet/ico-meet-location.svg
  src/_components/camp/CampDetail.tsx
  src/_components/common/CommunityTop.tsx
  src/_components/common/NoData.tsx
  src/_components/meet/MeetCard.tsx
  src/_components/weather/FutureWeather.tsx
  src/app/(pages)/meets/components/meets/WriteButton.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetContentSection.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetDetailController.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetIntroSection.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetSuppliesSection.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetTitleSection.tsx
  src/app/(pages)/meets/components/meetsList/MeetsList.tsx
  src/app/(pages)/meets/components/meetsWrite/MeetCreatorForm.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorContentSection.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorDateSection.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorHeadcountSection.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorInfoSection.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorSearchSection.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorTypeSection.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 스타일

#77 [style/all] SOS 페이지 스타일 1차 작업 PR
  src/_components/common/WriteButton.tsx
  src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorInfoSection.tsx
  src/app/(pages)/sos/components/sos/SosCard.tsx
  src/app/(pages)/sos/components/sosCreator/SosCreatorForm.tsx
  src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorContentSection.tsx
  src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorInfoSection.tsx
  src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorSearchSection.tsx
  src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorTagSection.tsx
  src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorTypeSection.tsx
  src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosTitleSection.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosUserSection.tsx
  src/app/(pages)/sos/page.tsx
Labels: 버그, 스타일

#82 [style/all] 캠핑 가이드 스타일 완료
  public/assets/images/guide/bg-guide-tip.png
  public/assets/images/guide/ico-guide-01.svg
  public/assets/images/guide/ico-guide-02.svg
  public/assets/images/guide/ico-guide-03.svg
  public/assets/images/guide/ico-guide-04.svg
  public/assets/images/guide/ico-guide-05.svg
  public/assets/images/guide/ico-guide-bulb.svg
  public/assets/images/guide/ico-guide-tip-01.svg
  public/assets/images/guide/ico-guide-tip-02.svg
  public/assets/images/guide/ico-guide-tip-03.svg
  public/assets/images/guide/ico-guide-tip-04.svg
  public/assets/images/guide/ico-guide-tip-05.svg
  public/assets/images/guide/ico-guide-tip-06.svg
  public/assets/images/guide/ico-guide-tip-07.svg
  public/assets/images/guide/ico-guide-tip-08.svg
  public/assets/images/guide/ico-guide-tip-09.svg
  public/assets/images/guide/ico-guide-tip-10.svg
  public/assets/images/guide/ico-guide-tip-11.svg
  src/_components/common/GuideTop.tsx
  src/_components/review/ReviewCard.tsx
  src/_utils/guide.js
  src/app/(pages)/(guide)/beginner/component/Card.tsx
  src/app/(pages)/(guide)/beginner/page.tsx
  src/app/(pages)/(guide)/campfire/page.tsx
  src/app/(pages)/(guide)/component/GuideCard.tsx
  src/app/(pages)/(guide)/etiquette/component/EtiquetteCard.tsx
  src/app/(pages)/(guide)/etiquette/page.tsx
  src/app/(pages)/(guide)/pet/page.tsx
  src/app/(pages)/(guide)/tip/component/TipCard.tsx
  src/app/(pages)/(guide)/tip/page.tsx
  src/app/(pages)/chat/page.tsx
  src/app/(pages)/mypage/MeetList.tsx
  src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosChatSection.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosContentSection.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosRemainingTimeSection.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosTagSection.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: ui, 스타일

#85 [style/all] 프로필 페이지, 마이페이지 1차 스타일 완료 (리뷰 제외)
  public/assets/images/common/ico-calendar-arrow-next.svg
  public/assets/images/common/ico-calendar-arrow-prev.svg
  public/assets/images/guide/ico-guide-bulb.svg
  public/assets/images/mypage/ico-mypage-fire.svg
  public/assets/images/mypage/ico-mypage-flag.svg
  public/assets/images/mypage/ico-mypage-hand.svg
  src/_components/bookmark/BookmarkList.tsx
  src/_components/calendar/CalendarCell.tsx
  src/_components/calendar/CalendarHeader.tsx
  src/_components/calendar/CalendarTable.tsx
  src/_components/follower/FollowCard.tsx
  src/_components/main/MainUserCard.tsx
  src/_components/star/Star.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetTitleSection.tsx
  src/app/(pages)/meets/components/meetsList/MeetsList.tsx
  src/app/(pages)/mypage/Bookmarks.tsx
  src/app/(pages)/mypage/CalendarFooter.tsx
  src/app/(pages)/mypage/CampingReviews.tsx
  src/app/(pages)/mypage/MeetList.tsx
  src/app/(pages)/profile/[userId]/page.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 버그, 스타일

#87 [Fix/SOS] [#86] - sos 상세에서 채팅 적용 안됨 외 1
  database.types.ts
  src/_components/chat/hooks/useChatSosMessage.ts
  src/_components/chat/service/chatService.ts
  src/_utils/supabase/supabase.rpc.ts
  src/app/(pages)/meets/actions/meetAttendAction.ts
  src/app/(pages)/meets/actions/meetWriteAction.ts
  src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosChatSection.tsx
Labels: 수정

#95 [style/all] 채팅 페이지, 모임 채팅 스타일 완료
  public/assets/images/common/ico-chat-user.svg
  src/_components/chat/ChatListCard.tsx
  src/_components/chat/ChatRoomMessageSection.tsx
  src/_components/chat/ChatRoomTitleSection.tsx
  src/app/(pages)/chat/[roomId]/page.tsx
  src/app/(pages)/chat/page.tsx
  src/app/(pages)/sos/components/sosDetail/section/SosChatSection.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 스타일

#96 [Feat/likes] - 리뷰 모달 상세화면 및 좋아요 기능 구현, 리팩토링 및 이슈 수정 적용
  public/assets/images/camp/btn-camp-like-active.svg
  public/assets/images/camp/btn-camp-like.svg
  src/_components/bookmark/BookmarkButton.tsx
  src/_components/bookmark/BookmarkList.tsx
  src/_components/camp/CampCard.tsx
  src/_components/camp/CampList.tsx
  src/_components/camp/CampReviewSlide.tsx
  src/_components/layout/Header.tsx
  src/_components/like/LikeButton.tsx
  src/_components/like/LikeList.tsx
  src/_components/main/MainReviews.tsx
  src/_components/meet/MeetCard.tsx
  src/_components/modal/Modal.tsx
  src/_components/review/ReviewCard.tsx
  src/_components/review/ReviewModal.tsx
  src/_components/review/ReviewSlideCard.tsx
  src/_utils/common/constant.ts
  src/_utils/serverActions/campApi.ts
  src/_utils/zustand/useLikeStore.ts
  src/app/(pages)/meets/components/meetsDetail/MeetTitleSection.tsx
  src/app/(pages)/meets/components/meetsList/MeetsList.tsx
  src/app/(pages)/mypage/Likes.tsx
  src/app/(pages)/mypage/TabList.tsx
  src/app/(pages)/mypage/page.tsx
  src/app/api/campApi/route.ts
  src/app/api/camping/route.ts
  src/app/globals.css
  src/app/queries/useQueries.ts
Labels: 리팩토링, 기능개발

#101 [style/all] 채팅, 캘린더 스타일 추가 수정 및 이슈사항 적용
  public/assets/images/common/img-camp-card.jpg
  public/assets/images/ico-group.svg
  public/assets/images/ico-location.svg
  src/_components/calendar/CalendarCell.tsx
  src/_components/calendar/utils/calenderService.ts
  src/_components/camp/CampCard.tsx
  src/_components/camp/CampReviewSlide.tsx
  src/_components/chat/ChatRoomMessageSection.tsx
  src/_components/main/MainReviews.tsx
  src/_components/main/MainUserCard.tsx
  src/_components/modal/ReviewWriteModal.tsx
  src/_components/review/ReviewCard.tsx
  src/app/(pages)/mypage/Likes.tsx
  src/app/(pages)/mypage/MeetList.tsx
Labels: 변경, 수정, 스타일

#120 [feat/interaction] 인터렉션 적용 전 스타일 수정 및 추가
  src/_components/camp/CampDetail.tsx
  src/_components/camp/CampList.tsx
  src/_components/chat/ChatListCard.tsx
  src/_components/layout/header/Header.tsx
  src/_hooks/useInteraction.ts
  src/app/(pages)/meets/components/meetsDetail/MeetDetailController.tsx
  src/app/(pages)/meets/components/meetsDetail/MeetIntroSection.tsx
  src/app/(pages)/sos/components/sos/SosList.tsx
  src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
  src/app/globals.css
Labels: 수정, 스타일
